module.exports = {
  apps: [
    {
      name: 'coin-front',
      script: '.venv/bin/python',
      args: '-c "from ui.web_server import run_server; run_server(port=8080)"',
      cwd: '/home/seedbot/Desktop/apps/CoinTrader',
      interpreter: 'none',
      out_file: 'logs/pm2/coin-front.out.log',
      error_file: 'logs/pm2/coin-front.err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env: {
        PYTHONUNBUFFERED: '1',
        COINTRADER_MANAGED_BY_PM2: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: 'coin-back',
      script: '.venv/bin/python',
      args: 'run_v2.py --mode live',
      cwd: '/home/seedbot/Desktop/apps/CoinTrader',
      interpreter: 'none',
      out_file: 'logs/pm2/coin-back.out.log',
      error_file: 'logs/pm2/coin-back.err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env: {
        PYTHONUNBUFFERED: '1',
        COINTRADER_DASHBOARD_RUNNING: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'ARGENT',
      script: '.venv/bin/python',
      args: 'argent_service.py',
      cwd: '/home/seedbot/Desktop/apps/CoinTrader',
      interpreter: 'none',
      out_file: 'logs/pm2/argent.out.log',
      error_file: 'logs/pm2/argent.err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
    },
  ],
};
